[project]
name = "iot-sensor-pipeline"
version = "0.1.0"
description = "IoT Sensor Data Collection & Processing Pipeline"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.2.3",
    "plotly>=6.1.1",
    "scipy>=1.15.3",
    "streamlit>=1.45.1",
]
